options:
  item-color: '#B5D1B6'
  item-linked: '[item]'
  npe-item-message: 'You have no items in your hand.'
  npe-message-color: '#B02C3A'
  npe-message-type: 'actionbar'

# message type : actionbar, message
# item-color, npe-message-color : hex code
